#!/usr/bin/env bash
# Sync media originals from the designers' prototype repo (EmbacyDev/Utopia).
#
# The designers' repo is the source of truth for raster/video media
# (latest iterations: desktop_v3 for desktop, v4 + root assets/ for mobile).
# Pairs below were derived by content hash (designer file == committed app file)
# on 2026-07-16. Re-run after designers push updates:  npm run sync:designer-media
#
# Usage: DESIGNER_REPO=../Utopia scripts/sync-designer-media.sh [--check]
#   --check  report differences without copying
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DESIGNER_REPO="${DESIGNER_REPO:-$ROOT/../Utopia}"
MODE="${1:-copy}"

if [ ! -d "$DESIGNER_REPO/.git" ]; then
  echo "designer repo not found at $DESIGNER_REPO (set DESIGNER_REPO=...)" >&2
  exit 1
fi

changed=0 missing=0 same=0
sync() {
  local src="$DESIGNER_REPO/$1" dst="$ROOT/$2"
  if [ ! -f "$src" ]; then
    echo "MISSING in designer repo: $1 (was source of $2)"; missing=$((missing+1)); return
  fi
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then same=$((same+1)); return; fi
  changed=$((changed+1))
  if [ "$MODE" = "--check" ]; then echo "DIFFERS: $1 -> $2"; else
    mkdir -p "$(dirname "$dst")"; cp "$src" "$dst"; echo "synced: $2"
  fi
}

sync "assets/LOGO-dark.svg" "public/assets/LOGO-dark.svg"
sync "assets/LOGO.svg" "public/assets/LOGO.svg"
sync "assets/beyond-jet.jpg" "public/assets/beyond-jet.jpg"
sync "assets/beyond-jet.png" "public/assets/beyond-jet.png"
sync "assets/beyond-yacht.jpg" "public/assets/beyond-yacht.jpg"
sync "assets/beyond-yacht.png" "public/assets/beyond-yacht.png"
sync "assets/chevron-dark.svg" "public/assets/chevron-dark.svg"
sync "assets/chevron-nav.svg" "public/assets/chevron-nav.svg"
sync "assets/chevron.svg" "public/assets/chevron.svg"
sync "assets/close-light.svg" "public/assets/close-light.svg"
sync "assets/close.svg" "public/assets/close.svg"
sync "assets/cta-nature.jpg" "public/assets/cta-nature.jpg"
sync "assets/cta-nature.png" "public/assets/cta-nature.png"
sync "assets/days-dining.jpg" "public/assets/days-dining.jpg"
sync "desktop_v3/assets/private-world-2.jpg" "public/assets/days-dining.png"
sync "assets/days-exclusively-yours.jpg" "public/assets/days-exclusively-yours.jpg"
sync "assets/days-exclusively-yours.png" "public/assets/days-exclusively-yours.png"
sync "assets/days-hyper-personal.png" "public/assets/days-hyper-personal.png"
sync "assets/days-water.jpg" "public/assets/days-water.jpg"
sync "assets/days-water.png" "public/assets/days-water.png"
sync "assets/days-wellness.jpg" "public/assets/days-wellness.jpg"
sync "desktop_v3/assets/private-world-3.jpg" "public/assets/days-wellness.png"
sync "desktop_v3/assets/arrow-icon.svg" "public/assets/desktop/arrow-icon.svg"
sync "desktop_v3/assets/chevron.svg" "public/assets/desktop/chevron.svg"
sync "desktop_v3/assets/dest-alpine-1.jpg" "public/assets/desktop/dest-alpine-1.jpg"
sync "desktop_v3/assets/dest-tropical-1.jpg" "public/assets/desktop/dest-tropical-1.jpg"
sync "desktop_v3/assets/dest-tropical-2.jpg" "public/assets/desktop/dest-tropical-2.jpg"
sync "desktop_v3/assets/dest-tropical-3.jpg" "public/assets/desktop/dest-tropical-3.jpg"
sync "desktop_v3/assets/dest-tropical-4.jpg" "public/assets/desktop/dest-tropical-4.jpg"
sync "desktop_v3/assets/dest-tropical-5.jpg" "public/assets/desktop/dest-tropical-5.jpg"
sync "desktop_v3/assets/dest-urban-1.jpg" "public/assets/desktop/dest-urban-1.jpg"
sync "desktop_v3/assets/dest-urban-2.jpg" "public/assets/desktop/dest-urban-2.jpg"
sync "desktop_v3/assets/dest-urban-3.jpg" "public/assets/desktop/dest-urban-3.jpg"
sync "desktop_v3/assets/footer-rock.jpg" "public/assets/desktop/footer-rock.jpg"
sync "desktop_v3/assets/footer-social-facebook.svg" "public/assets/desktop/footer-social-facebook.svg"
sync "desktop_v3/assets/footer-social-instagram.svg" "public/assets/desktop/footer-social-instagram.svg"
sync "desktop_v3/assets/footer-social-linkedin.svg" "public/assets/desktop/footer-social-linkedin.svg"
sync "desktop_v3/assets/footer-social-telegram.svg" "public/assets/desktop/footer-social-telegram.svg"
sync "desktop_v3/assets/footer-social-whatsapp.svg" "public/assets/desktop/footer-social-whatsapp.svg"
sync "desktop_v3/assets/fullwidth-birds.mp4" "public/assets/desktop/fullwidth-birds.mp4"
sync "desktop_v3/assets/fullwidth-birds.png" "public/assets/desktop/fullwidth-birds.png"
sync "desktop_v3/assets/fullwidth-birds.webm" "public/assets/desktop/fullwidth-birds.webm"
sync "desktop_v3/assets/fullwidth-dunes.mp4" "public/assets/desktop/fullwidth-dunes.mp4"
sync "desktop_v3/assets/fullwidth-dunes.png" "public/assets/desktop/fullwidth-dunes.png"
sync "desktop_v3/assets/fullwidth-dunes.webm" "public/assets/desktop/fullwidth-dunes.webm"
sync "desktop_v3/assets/fullwidth-kitesurfing.mp4" "public/assets/desktop/fullwidth-kitesurfing.mp4"
sync "desktop_v3/assets/fullwidth-kitesurfing.png" "public/assets/desktop/fullwidth-kitesurfing.png"
sync "desktop_v3/assets/fullwidth-kitesurfing.webm" "public/assets/desktop/fullwidth-kitesurfing.webm"
sync "desktop_v3/assets/hero-bg-1920.jpg" "public/assets/desktop/hero-bg-1920.jpg"
sync "desktop_v3/assets/hero-bg-barcelona.jpg" "public/assets/desktop/hero-bg-barcelona.jpg"
sync "desktop_v3/assets/hero-bg-barcelona.mp4" "public/assets/desktop/hero-bg-barcelona.mp4"
sync "desktop_v3/assets/hero-bg-cabarete.jpg" "public/assets/desktop/hero-bg-cabarete.jpg"
sync "desktop_v3/assets/hero-bg-cabarete.mp4" "public/assets/desktop/hero-bg-cabarete.mp4"
sync "desktop_v3/assets/hero-bg-capetown.jpg" "public/assets/desktop/hero-bg-capetown.jpg"
sync "desktop_v3/assets/hero-bg-capetown.mp4" "public/assets/desktop/hero-bg-capetown.mp4"
sync "desktop_v3/assets/hero-bg-dubai.jpg" "public/assets/desktop/hero-bg-dubai.jpg"
sync "desktop_v3/assets/hero-bg-dubai.mp4" "public/assets/desktop/hero-bg-dubai.mp4"
sync "desktop_v3/assets/hero-bg-flora.jpg" "public/assets/desktop/hero-bg-flora.jpg"
sync "desktop_v3/assets/hero-bg-flora.mp4" "public/assets/desktop/hero-bg-flora.mp4"
sync "desktop_v3/assets/hero-bg-jericoacoara.jpg" "public/assets/desktop/hero-bg-jericoacoara.jpg"
sync "desktop_v3/assets/hero-bg-jericoacoara.mp4" "public/assets/desktop/hero-bg-jericoacoara.mp4"
sync "desktop_v3/assets/hero-bg-roca.jpg" "public/assets/desktop/hero-bg-roca.jpg"
sync "desktop_v3/assets/hero-bg-roca.mp4" "public/assets/desktop/hero-bg-roca.mp4"
sync "desktop_v3/assets/logo-icon.svg" "public/assets/desktop/logo-icon.svg"
sync "desktop_v3/assets/nav-arrow-black.svg" "public/assets/desktop/nav-arrow-black.svg"
sync "desktop_v3/assets/nav-menu-aviation.jpg" "public/assets/desktop/nav-menu-aviation.jpg"
sync "desktop_v3/assets/nav-menu-bg.jpg" "public/assets/desktop/nav-menu-bg.jpg"
sync "desktop_v3/assets/nav-menu-icon.svg" "public/assets/desktop/nav-menu-icon.svg"
sync "desktop_v3/assets/nav-menu-superyacht.jpg" "public/assets/desktop/nav-menu-superyacht.jpg"
sync "desktop_v3/assets/nav-menu-tropical.jpg" "public/assets/desktop/nav-menu-tropical.jpg"
sync "desktop_v3/assets/nav-pill-menu.svg" "public/assets/desktop/nav-pill-menu.svg"
sync "desktop_v3/assets/pw-1.jpg" "public/assets/desktop/pw-1.jpg"
sync "desktop_v3/assets/pw-2.jpg" "public/assets/desktop/pw-2.jpg"
sync "desktop_v3/assets/pw-3.jpg" "public/assets/desktop/pw-3.jpg"
sync "desktop_v3/assets/social-icons-nav.svg" "public/assets/desktop/social-icons-nav.svg"
sync "assets/dunes.mp4" "public/assets/dunes.mp4"
sync "assets/ecosystem-bg-2.jpg" "public/assets/ecosystem-bg-2.jpg"
sync "assets/ecosystem-bg-alpine.png" "public/assets/ecosystem-bg-alpine.png"
sync "assets/ecosystem-bg-barcelona-urban.png" "public/assets/ecosystem-bg-barcelona-urban.png"
sync "assets/ecosystem-bg-cabarete-tropical.png" "public/assets/ecosystem-bg-cabarete-tropical.png"
sync "assets/ecosystem-bg-alpine.png" "public/assets/ecosystem-bg-capetown-urban.png"
sync "assets/ecosystem-bg-dubai-urban.png" "public/assets/ecosystem-bg-dubai-urban.png"
sync "assets/ecosystem-bg-jeri-lobby.png" "public/assets/ecosystem-bg-jeri-lobby.png"
sync "assets/ecosystem-bg-prea-tropical.png" "public/assets/ecosystem-bg-prea-tropical.png"
sync "assets/ecosystem-bg-roca-tropical.png" "public/assets/ecosystem-bg-roca-tropical.png"
sync "desktop_v3/assets/dest-urban-2.jpg" "public/assets/enhanced_ecosystem-bg-barcelona-urban.png"
sync "desktop_v3/assets/dest-tropical-5.jpg" "public/assets/enhanced_ecosystem-bg-cabarete-tropical.png"
sync "assets/enhanced_ecosystem-bg-dubai-urban.png" "public/assets/enhanced_ecosystem-bg-dubai-urban.png"
sync "assets/enhanced_ecosystem-bg-flora-tropical.png" "public/assets/enhanced_ecosystem-bg-flora-tropical.png"
sync "assets/enhanced_ecosystem-bg-jeri-lobby.png" "public/assets/enhanced_ecosystem-bg-jeri-lobby.png"
sync "desktop_v3/assets/dest-tropical-3.jpg" "public/assets/enhanced_ecosystem-bg-prea-tropical.png"
sync "assets/enhanced_ecosystem-bg-roca-tropical.png" "public/assets/enhanced_ecosystem-bg-roca-tropical.png"
sync "assets/enhanced_hero-bg-barcelona-urban.png" "public/assets/enhanced_hero-bg-barcelona-urban.png"
sync "assets/enhanced_hero-bg-cabarete.png" "public/assets/enhanced_hero-bg-cabarete.png"
sync "assets/enhanced_hero-bg-flora.png" "public/assets/enhanced_hero-bg-flora.png"
sync "assets/enhanced_hero-bg-jericoacoara-suite.png" "public/assets/enhanced_hero-bg-jericoacoara-suite.png"
sync "assets/enhanced_hero-bg-roca.png" "public/assets/enhanced_hero-bg-roca.png"
sync "assets/experience-dining.jpg" "public/assets/experience-dining.jpg"
sync "assets/days-water.jpg" "public/assets/experience-water.jpg"
sync "assets/days-wellness.jpg" "public/assets/experience-wellness.jpg"
sync "assets/footer.mp4" "public/assets/footer.mp4"
sync "assets/footer.webm" "public/assets/footer.webm"
sync "assets/hero-bg-barcelona-urban.png" "public/assets/hero-bg-barcelona-urban.png"
sync "assets/hero-bg-cabarete.png" "public/assets/hero-bg-cabarete.png"
sync "assets/hero-bg-cape-town.jpg" "public/assets/hero-bg-cape-town.jpg"
sync "assets/hero-bg-dubai.jpg" "public/assets/hero-bg-dubai.jpg"
sync "assets/hero-bg-jericoacoara-suite.png" "public/assets/hero-bg-jericoacoara-suite.png"
sync "assets/hero-bg-roca.png" "public/assets/hero-bg-roca.png"
sync "assets/hero-emblem.svg" "public/assets/hero-emblem.svg"
sync "assets/chevron-dark.svg" "public/assets/icons/chevron-dark.svg"
sync "assets/menu.svg" "public/assets/icons/close.svg"
sync "desktop_v3/assets/instagram-icon.svg" "public/assets/icons/footer-arrow-up.svg"
sync "assets/hero-emblem.svg" "public/assets/icons/home-mark.svg"
sync "assets/logo-mark.svg" "public/assets/icons/logo-mark.svg"
sync "assets/logo-wordmark-dark.svg" "public/assets/icons/logo-wordmark.svg"
sync "assets/menu.svg" "public/assets/icons/menu.svg"
sync "assets/beyond-jet.jpg" "public/assets/jet.jpg"
sync "assets/jet.mp4" "public/assets/jet.mp4"
sync "assets/kitesurf.mp4" "public/assets/kitesurf.mp4"
sync "assets/localvibes.mp4" "public/assets/localvibes.mp4"
sync "assets/logo-mark-dark.svg" "public/assets/logo-mark-dark.svg"
sync "assets/logo-mark.svg" "public/assets/logo-mark.svg"
sync "assets/logo-wordmark-compact.png" "public/assets/logo-wordmark-compact.png"
sync "assets/logo-wordmark-dark.svg" "public/assets/logo-wordmark-dark.svg"
sync "assets/logo-wordmark.svg" "public/assets/logo-wordmark.svg"
sync "assets/menu-light.svg" "public/assets/menu-light.svg"
sync "assets/menu.svg" "public/assets/menu.svg"
sync "desktop_v3/assets/nav-arrow-black.svg" "public/assets/menu/link-chevron.svg"
sync "desktop_v3/assets/nav-chevron-down.svg" "public/assets/menu/menu-chevron-down.svg"
sync "desktop_v3/assets/nav-menu-aviation.jpg" "public/assets/menu/nav-menu-aviation.jpg"
sync "desktop_v3/assets/nav-menu-superyacht.jpg" "public/assets/menu/nav-menu-superyacht.jpg"
sync "desktop_v3/assets/nav-menu-tropical.jpg" "public/assets/menu/nav-menu-tropical.jpg"
sync "assets/opening-dunes.jpg" "public/assets/opening-dunes.jpg"
sync "assets/opening-kite.jpg" "public/assets/opening-kite.jpg"
sync "assets/opening-localvibes.jpg" "public/assets/opening-localvibes.jpg"
sync "assets/opening-slide-1a.jpg" "public/assets/opening-slide-1a.jpg"
sync "assets/opening-slide-1b.jpg" "public/assets/opening-slide-1b.jpg"
sync "assets/opening-slide-1c.jpg" "public/assets/opening-slide-1c.jpg"
sync "assets/opening-slide-1c.png" "public/assets/opening-slide-1c.png"
sync "assets/opening-slide-2.jpg" "public/assets/opening-slide-2.jpg"
sync "assets/opening-slide-2.png" "public/assets/opening-slide-2.png"
sync "assets/opening-slide-3.jpg" "public/assets/opening-slide-3.jpg"
sync "assets/opening-slide-3.png" "public/assets/opening-slide-3.png"
sync "assets/opening-slide-2.jpg" "public/assets/opening-tropics.jpg"
sync "assets/opening-wellness.jpg" "public/assets/opening-wellness.jpg"
sync "assets/opt/beyond-jet.jpg" "public/assets/opt/beyond-jet.jpg"
sync "assets/opt/beyond-yacht.jpg" "public/assets/opt/beyond-yacht.jpg"
sync "assets/opt/cta-footer-poster.jpg" "public/assets/opt/cta-footer-poster.jpg"
sync "assets/opt/cta-nature.jpg" "public/assets/opt/cta-nature.jpg"
sync "assets/opt/days-dining.jpg" "public/assets/opt/days-dining.jpg"
sync "assets/opt/days-exclusively-yours.jpg" "public/assets/opt/days-exclusively-yours-mobile.jpg"
sync "desktop_v3/assets/private-world-1.jpg" "public/assets/opt/days-exclusively-yours.jpg"
sync "assets/opt/days-hyper-personal.jpg" "public/assets/opt/days-hyper-personal.jpg"
sync "assets/opt/days-water.jpg" "public/assets/opt/days-water.jpg"
sync "assets/days-water.png" "public/assets/opt/days-water.png"
sync "assets/opt/days-wellness.jpg" "public/assets/opt/days-wellness.jpg"
sync "assets/dunes.mp4" "public/assets/opt/dunes.mp4"
sync "assets/opt/ecosystem-bg-2.jpg" "public/assets/opt/ecosystem-bg-2.jpg"
sync "assets/opt/ecosystem-bg-alpine.jpg" "public/assets/opt/ecosystem-bg-alpine.jpg"
sync "assets/opt/ecosystem-bg-capetown-urban.jpg" "public/assets/opt/ecosystem-bg-capetown-urban.jpg"
sync "assets/opt/enhanced_ecosystem-bg-barcelona-urban.jpg" "public/assets/opt/enhanced_ecosystem-bg-barcelona-urban.jpg"
sync "assets/opt/enhanced_ecosystem-bg-cabarete-tropical.jpg" "public/assets/opt/enhanced_ecosystem-bg-cabarete-tropical.jpg"
sync "assets/opt/enhanced_ecosystem-bg-dubai-urban.jpg" "public/assets/opt/enhanced_ecosystem-bg-dubai-urban.jpg"
sync "assets/opt/enhanced_ecosystem-bg-flora-tropical.jpg" "public/assets/opt/enhanced_ecosystem-bg-flora-tropical.jpg"
sync "assets/opt/enhanced_ecosystem-bg-jeri-lobby.jpg" "public/assets/opt/enhanced_ecosystem-bg-jeri-lobby.jpg"
sync "assets/opt/enhanced_ecosystem-bg-prea-tropical.jpg" "public/assets/opt/enhanced_ecosystem-bg-prea-tropical.jpg"
sync "assets/opt/enhanced_ecosystem-bg-roca-tropical.jpg" "public/assets/opt/enhanced_ecosystem-bg-roca-tropical.jpg"
sync "assets/opt/enhanced_hero-bg-barcelona-urban.jpg" "public/assets/opt/enhanced_hero-bg-barcelona-urban.jpg"
sync "assets/opt/enhanced_hero-bg-cabarete.jpg" "public/assets/opt/enhanced_hero-bg-cabarete.jpg"
sync "assets/opt/enhanced_hero-bg-flora.jpg" "public/assets/opt/enhanced_hero-bg-flora.jpg"
sync "assets/opt/enhanced_hero-bg-jericoacoara-suite.jpg" "public/assets/opt/enhanced_hero-bg-jericoacoara-suite.jpg"
sync "assets/opt/enhanced_hero-bg-roca.jpg" "public/assets/opt/enhanced_hero-bg-roca.jpg"
sync "assets/opt/hero-bg-cape-town.jpg" "public/assets/opt/hero-bg-cape-town.jpg"
sync "assets/opt/hero-bg-dubai.jpg" "public/assets/opt/hero-bg-dubai.jpg"
sync "assets/opt/jet.mp4" "public/assets/opt/jet.mp4"
sync "assets/opt/jet.webm" "public/assets/opt/jet.webm"
sync "assets/kitesurf.mp4" "public/assets/opt/kitesurf.mp4"
sync "assets/localvibes.mp4" "public/assets/opt/localvibes.mp4"
sync "assets/opt/opening-dunes.jpg" "public/assets/opt/opening-dunes.jpg"
sync "assets/opt/opening-kitesurf.jpg" "public/assets/opt/opening-kitesurf.jpg"
sync "assets/opening-localvibes.jpg" "public/assets/opt/opening-localvibes.jpg"
sync "assets/opt/opening-tropics.jpg" "public/assets/opt/opening-tropics.jpg"
sync "assets/opt/opening-wellness.jpg" "public/assets/opt/opening-wellness.jpg"
sync "assets/opt/tropics.mp4" "public/assets/opt/tropics.mp4"
sync "assets/opt/tropics.webm" "public/assets/opt/tropics.webm"
sync "assets/opt/wellness.mp4" "public/assets/opt/wellness.mp4"
sync "assets/opt/wellness.webm" "public/assets/opt/wellness.webm"
sync "assets/opt/yacht.mp4" "public/assets/opt/yacht.mp4"
sync "assets/opt/yacht.webm" "public/assets/opt/yacht.webm"
sync "assets/search-light.svg" "public/assets/search-light.svg"
sync "assets/search.svg" "public/assets/search.svg"
sync "assets/tropics.mp4" "public/assets/tropics.mp4"
sync "assets/wellness.mp4" "public/assets/wellness.mp4"
sync "assets/beyond-yacht.jpg" "public/assets/yacht.jpg"
sync "assets/yacht.mp4" "public/assets/yacht.mp4"

echo "done: $same unchanged, $changed differing/synced, $missing missing sources"
if [ "$MODE" != "--check" ] && [ "$changed" -gt 0 ]; then
  # Next's dev image optimizer caches derivatives by filename; in-place byte
  # replacements keep serving stale images until the cache is cleared.
  echo "note: files changed — clear the dev image cache before eyeballing: rm -rf .next/cache/images"
fi
